### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke 

### ISSUE THREAD

**Issue by Ixf1nity** [IncrediblePlugins/LandsAPI#22]
[12:37:00 INFO]: [ClanNexus] Enabling ClanNexus v1.0-SNAPSHOT
[12:37:00 ERROR]: Error occurred while enabling ClanNexus v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.angeschossen.lands.api.handler.LandsIntegrationFactory.of(org.bukkit.plugin.Plugin)" because the return value of "me.angeschossen.lands.api.handler.APIHandler.getLandsIntegrationFactory()" is null
        at me.angeschossen.lands.api.LandsIntegration.of(LandsIntegration.java:35) ~[clanexus-1.0-SNAPSHOT.jar:?]
        at in.arcadelabs.clanexus.ClanNexus.onEnable(ClanNexus.java:26) ~[clanexus-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]

**Comment by Angeschossen** [comment]
Make sure to access the API only after Lands is loaded.
