### ISSUE TITLE
IllegalPluginAccessException

### ISSUE THREAD

**Issue by Deichor** [IncrediblePlugins/LandsAPI#30]
```
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event me.angeschossen.lands.api.framework.events.PluginEvent. Static getHandlerList method required!
	at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:124) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:122) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:122) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:122) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:122) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:84) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:136) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:683) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at ozClaim.jar/com.deichor.ozclaim.ozClaim.onEnable(ozClaim.java:53) ~[ozClaim.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:779) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:526) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[folia-1.21.1.jar:1.21.1-DEV-5833269]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Angeschossen** [comment]
PluginEvent is an abstract class and not an event that you can listen to.

**Comment by Deichor** [comment]
> PluginEvent is an abstract class and not an event that you can listen to.

I'm not trying to listen to PluginEvent; I'm trying to listen to LandBlockInteractEvent.

**Comment by Angeschossen** [comment]
The event has the said method. Please make sure you use the latest version.
